local L = AceLibrary("AceLocale-2.2"):new("MikScrollingBattleText")

L:RegisterTranslations("deDE", function()
    return {
		["Debug mode has been enabled."] = "Debug mode has been enabled.",
		["Debug mode has been disabled."] = "Debug mode has been disabled.",
		["Event search mode has been enabled.  Searching for: "] = "Event search mode has been enabled.  Searching for: ",
		["Event search mode has been disabled."] = "Event search mode has been disabled.",
		["The mod is now disabled."] = "The mod is now disabled.",
		["The mod is now enabled."] = "The mod is now enabled.",
		["Hits"] = "Treffer",
		["Crit"] = "Krit",
		["Crits"] = "Krits",
		["Multiple"] = "Mehrere",
		[" (%d vulnerability)"] = " (%d vulnerability)",
		[" <\124cff00b37e\124h%d\124h\124r>"] = " <\124cff00b37e\124h%d\124h\124r>",
		["Profile Reset"] = "Profile Reset",
		["Drowning"] = "Drowning",
		["Falling"] = "Falling",
		["Fatigue"] = "Fatigue",
		["Fire"] = "Fire",
		["Lava"] = "Lava",
		["Slime"] = "Slime",
		["Windfury!"] = nil,
		["Low Mana! (%1)"] = nil,
		["Low Pet Health! (%1)"] = nil,
		["%a CP Finish It!"] = nil,
		["+Combat"] = nil,
		["-Combat"] = nil,
		["%a CP"] = nil,
		["Pet "] = nil,
		["Pet %a (%s)"] = nil,
		["Pet %a"] = nil,
		["-%a (Pet)"] = nil,
		["! (Pet)"] = nil,
		["+%a (%n) (Pet)"] = nil,
		["Killing Blow! (%s)"] = nil,
		["Low Health! (%1)"] = nil,
    }
end)