local L = AceLibrary("AceLocale-2.2"):new("MikScrollingBattleText")

L:RegisterTranslations("enUS", function()
	return {
		["Debug mode has been enabled."] = true,
		["Debug mode has been disabled."] = true,
		["Event search mode has been enabled.  Searching for: "] = true,
		["Event search mode has been disabled."] = true,
		["The mod is now disabled."] = true,
		["The mod is now enabled."] = true,
		["Hits"] = true,
		["Crit"] = true,
		["Crits"] = true,
		["Multiple"] = true,
		[" (%d vulnerability)"] = true,
		[" <\124cff00b37e\124h%d\124h\124r>"] = true,
		["Profile Reset"] = true,
		["Drowning"] = true,
		["Falling"] = true,
		["Fatigue"] = true,
		["Fire"] = true,
		["Lava"] = true,
		["Slime"] = true,
		["Windfury!"] = true,
		["Low Mana! (%1)"] = true,
		["Low Pet Health! (%1)"] = true,
		["%a CP Finish It!"] = true,
		["+Combat"] = true,
		["-Combat"] = true,
		["%a CP"] = true,
		["Pet "] = true,
		["Pet %a (%s)"] = true,
		["Pet %a"] = true,
		["-%a (Pet)"] = true,
		["! (Pet)"] = true,
		["+%a (%n) (Pet)"] = true,
		["Killing Blow! (%s)"] = true,
		["Low Health! (%1)"] = true,
	}
end)